sudo: required
services:
  - docker
before_install:
  - docker build -t vishalsingh1988/docker-react -f Dockerfile .
script:
  - docker run -e CI=true vishalsingh1988/docker-react
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-667116000798"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


